/**
 * SegmentManager web UI constants.
 */

var SERVICE_PREFIX = "/customerprofile/";
var ATTRIBUTE_LIST_SERVICE = "fetchattributes/";
var ATTRIBUTE_DETAILS_SERVICE = "getattributesvalue/";
var FILTERDATA_LIST_SERVICE = "getcustomerdata/";
var SAVE_SEGMENT_DEFINATION_SERVICES = "savesegmentdefinition";
var SEGMENT_LIST_SERVICE = "fetchallsegments/";
var UPDATE_SEGMENT_DATA_SERVICE = "updatesegments";
var UPDATE_SEGMENT_STATUS_SERVICE = "updatesegmentstatus";

var SEGMENT_LIST = {
    "filterCriterias": [
        {
            "filterName": "segmentCategory",
            "filterType": "list",
            "filterValue": [
                "ACCOUNT_CUSTOMER",
                "CONTACT_CUSTOMER"
            ]
        },
        {
            "filterName": "user",
            "filterType": "string",
            "filterValue": []
        },
        {
            "filterName": "segmentName",
            "filterType": "string",
            "filterValue": []
        },
        {
            "filterName": "createdDate",
            "filterType": "Date",
            "filterValue": []
        },
        {
            "filterName": "segmentStatus",
            "filterType": "list",
            "filterValue": [
                "active",
                "archive"
            ]
        }
    ],
    "segmentDefinitionsList": [
        {
            "segmentId": "22017914",
            "user": "NewUser",
            "createdDate": "2017-09-14",
            "createdTime": "18:56:02.002",
            "segmentName": "FGH",
            "segmentDefination": "THIS IS OK",
            "segmentFilter": "mail_and_ship_12_months_spend >= 390975.52&office_supplies_3_months_spend >= 482958.484",
            "segmentStatus": "active",
            "segmentCategory": "ACCOUNT_CUSTOMER",
            "hashValue": 564834776,
            "updatedDate": null,
            "updatedTime": null,
            "updatedBy": null
        },
        {
            "segmentId": "2242017914",
            "user": "NewUser",
            "createdDate": "2017-09-14",
            "createdTime": "19:35:35.224",
            "segmentName": "src_sys_code_test_001",
            "segmentDefination": "src_sys_code_test",
            "segmentFilter": "src_sys_code = 19",
            "segmentStatus": "active",
            "segmentCategory": "ACCOUNT_CUSTOMER",
            "hashValue": -1150618433,
            "updatedDate": null,
            "updatedTime": null,
            "updatedBy": null
        },
        {
            "segmentId": "6582017919",
            "user": "NewUser",
            "createdDate": "2017-09-19",
            "createdTime": "15:15:27.658",
            "segmentName": "division_SPS-SBA_001",
            "segmentDefination": "division_SPS-SBA_001_test",
            "segmentFilter": "division = SPS-SBA",
            "segmentStatus": "active",
            "segmentCategory": "ACCOUNT_CUSTOMER",
            "hashValue": -2119073091,
            "updatedDate": null,
            "updatedTime": null,
            "updatedBy": null
        },
        {
            "segmentId": "5522017912",
            "user": "NewUser",
            "createdDate": "2017-09-12",
            "createdTime": "19:53:14.552",
            "segmentName": "facilities_12_months_spend_12",
            "segmentDefination": "facilities_12_months_spend_test",
            "segmentFilter": "facilities_12_months_spend >= 633308&facilities_12_months_spend <= 12286177",
            "segmentStatus": "active",
            "segmentCategory": "ACCOUNT_CUSTOMER",
            "hashValue": -1217351189,
            "updatedDate": null,
            "updatedTime": null,
            "updatedBy": null
        },
        {
            "segmentId": "6662017912",
            "user": "NewUser",
            "createdDate": "2017-09-12",
            "createdTime": "19:36:46.667",
            "segmentName": "facilities_3_months_spend_test_11",
            "segmentDefination": "facilities_3_months_spend_test",
            "segmentFilter": "facilities_3_months_spend >= 2095165&facilities_3_months_spend <= 2648056",
            "segmentStatus": "archive",
            "segmentCategory": "ACCOUNT_CUSTOMER",
            "hashValue": -2125919059,
            "updatedDate": null,
            "updatedTime": null,
            "updatedBy": null
        },
        {
            "segmentId": "4772017914",
            "user": "NewUser",
            "createdDate": "2017-09-14",
            "createdTime": "19:34:23.477",
            "segmentName": "nat test",
            "segmentDefination": "nat_test",
            "segmentFilter": "division = NAT",
            "segmentStatus": "active",
            "segmentCategory": "ACCOUNT_CUSTOMER",
            "hashValue": -1008683981,
            "updatedDate": null,
            "updatedTime": null,
            "updatedBy": null
        },
        {
            "segmentId": "2432017914",
            "user": "NewUser",
            "createdDate": "2017-09-14",
            "createdTime": "18:53:39.244",
            "segmentName": "division_001",
            "segmentDefination": "division_001_test",
            "segmentFilter": "division = NYC",
            "segmentStatus": "active",
            "segmentCategory": "ACCOUNT_CUSTOMER",
            "hashValue": -687010380,
            "updatedDate": null,
            "updatedTime": null,
            "updatedBy": null
        },
        {
            "segmentId": "5542017914",
            "user": "NewUser",
            "createdDate": "2017-09-14",
            "createdTime": "10:06:19.554",
            "segmentName": "zip_code_001",
            "segmentDefination": "zip_code_test",
            "segmentFilter": "zip_code = 25130",
            "segmentStatus": "active",
            "segmentCategory": "ACCOUNT_CUSTOMER",
            "hashValue": 840283839,
            "updatedDate": null,
            "updatedTime": null,
            "updatedBy": null
        }
    ]
};


var ATTRIBUTE_LIST_UPDATED = [
    {
        "grpName": "ACCOUNT_CUSTOMER_BANK",
        "hrcNames": [
            {
                "hrcName": "Identifier",
                "attributeList": [
                    {
                        "name": "account_number",
                        "type": "string",
                        "isAdded": false
                    },
                    {
                        "name": "src_sys_code",
                        "type": "string",
                        "isAdded": false
                    },
                    {
                        "name": "account_type_code",
                        "type": "string",
                        "isAdded": false
                    },
                    {
                        "name": "account_type",
                        "type": "string",
                        "isAdded": false
                    },
                    {
                        "name": "division",
                        "type": "string",
                        "isAdded": false
                    },
                    {
                        "name": "company",
                        "type": "string",
                        "isAdded": false
                    }
                ]
            },
            {
                "hrcName": "Category_Spend",
                "attributeList": [
                    {
                        "name": "facilities_12_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "facilities_3_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "mail_and_ship_12_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "office_supplies_3_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "print_24_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "promo_12_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "toner_12_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "food_and_brkrm_12_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "food_and_brkrm_6_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "furniture_12_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "furniture_24_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "mail_and_ship_6_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "paper_24_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "print_6_months_spend ",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "tech_24_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "toner_24_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "toner_6_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "facilities_24_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "facilities_6_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "food_and_brkrm_24_mths_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "food_and_brkrm_3_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "furniture_6_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "mail_and_ship_24_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "mail_and_ship_3_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "tech_3_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "tech_6_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "toner_3_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "furniture_3_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "office_supplies_12_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "office_supplies_24_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "paper_6_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "print_12_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "print_3_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "promo_6_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "tech_12_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "office_supplies_6_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "paper_12_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "paper_3_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "promo_24_months_spend",
                        "type": "float",
                        "isAdded": false
                    },
                    {
                        "name": "promo_3_months_spend",
                        "type": "float",
                        "isAdded": false
                    }
                ]
            },
            {
                "hrcName": "Firmographics",
                "attributeList": [
                    {
                        "name": "zip_code",
                        "type": "string",
                        "isAdded": false
                    },
                    {
                        "name": "state",
                        "type": "string",
                       "isAdded": false
                    }
                ]
            },
            {
                "hrcName": "Membership",
                "attributeList": [
                    {
                        "name": "memb_end_date",
                        "type": "date",
                        "isAdded": false
                    },
                    {
                        "name": "memb_start_date",
                        "type": "date",
                        "isAdded": false
                    },
                    {
                        "name": "rewards_account_number",
                        "type": "string",
                        "isAdded": false
                    },
                    {
                        "name": "rewards_tier",
                        "type": "string",
                        "isAdded": false
                    },
                    {
                        "name": "memb_enrolled_flag",
                        "type": "string",
                        "isAdded": false
                    },
                    {
                        "name": "enrolled_prog",
                        "type": "string",
                        "isAdded": false
                    },
                    {
                        "name": "rewards_start_dat",
                        "type": "date",
                        "isAdded": false
                    }
                ]
            }
        ]
    }
];

var TABLE_LIST = {
    "result_count": 85923,
    "dataList": [
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        }],
    };

    var ATTRIBUTE_DESCRIPTION_ = {
        "maxValue":7512402.0,
        "minValue":-120000.0
        };

    var ATTRIBUTE_DESCRIPTION = [
        "DE",
        "TX",
        "FL",
        "NV",
        "WA",
        "NY",
        "SC",
        "SD",
        "WI",
        "MA",
        "MD",
        "IA",
        "ME",
        "OH",
        "GA",
        "ID",
        "MI",
        "OK",
        "CA",
        "WV",
        "UT",
        "MN",
        "WY",
        "MO",
        "IL",
        "OR",
        "IN",
        "MS",
        "MT",
        "KS",
        "AL",
        "VA",
        "CO",
        "KY",
        "PA",
        "CT",
        "AR",
        "NC",
        "LA",
        "NE",
        "RI",
        "AZ",
        "TN",
        "NH",
        "NJ",
        "VT",
        "DC",
        "NM"
        ];
    
