/**
 * SegmentManager web UI constants.
 */

var SERVICE_PREFIX = "http://10.100.40.220:8090/customerprofile/";
var ATTRIBUTE_LIST_SERVICE = "fetchattributes/";
var ATTRIBUTE_DETAILS_SERVICE = "getattributesvalue/";
var FILTERDATA_LIST_SERVICE = "getcustomerdata/";
var SAVE_SEGMENT_DEFINATION_SERVICES = "savesegmentdefinition";
var SEGMENT_LIST_SERVICE = "fetchallsegments/";
var UPDATE_SEGMENT_DATA_SERVICE = "updatesegments";
var UPDATE_SEGMENT_STATUS_SERVICE = "updatesegmentstatus";

var SEGMENT_LIST = [
    {
        "segmentId": "86103991712541936042017-08-24T14:47:41.476",
        "user": "currentUser",
        "createdDateTime": "2017-08-24T14:47:41.476",
        "segmentName": "state wise search",
        "segmentDefination": "state BC and UT",
        "segmentFilter": "state = BC,UT",
        "segmentStatus": "Active",
        "segmentCategory": "ACCOUNT_CUSTOMER"
    },
    {
        "segmentId": "8610399171254194088",
        "user": "NewUser",
        "createdDateTime": "2017-08-25T18:16:37.484",
        "segmentName": "sayonee",
        "segmentDefination": "test2",
        "segmentFilter": "mail_and_ship_12_months_spend <= 1483844.52",
        "segmentStatus": "Archive",
        "segmentCategory": "ACCOUNT_CUSTOMER"
    },
    {
        "segmentId": "8610399171254194028",
        "user": "NewUser",
        "createdDateTime": "2017-08-25T18:31:50.424",
        "segmentName": "fdd",
        "segmentDefination": "sdsfsf",
        "segmentFilter": "facilities_12_months_spend = 0",
        "segmentStatus": "Active",
        "segmentCategory": "ACCOUNT_CUSTOMER"
    },
    {
        "segmentId": "8610399171254193819",
        "user": "NewUser",
        "createdDateTime": "2017-08-25T15:13:36.215",
        "segmentName": "test25/08",
        "segmentDefination": "test25/08",
        "segmentFilter": "division=ATL",
        "segmentStatus": "Active",
        "segmentCategory": "ACCOUNT_CUSTOMER"
    },
    {
        "segmentId": "8610399171254193829",
        "user": "NewUser",
        "createdDateTime": "2017-08-25T18:08:44.225",
        "segmentName": "Test25/08 facilities",
        "segmentDefination": "FacilitiesCheck",
        "segmentFilter": "facilities_12_months_spend >= 12666162",
        "segmentStatus": "Active",
        "segmentCategory": "ACCOUNT_CUSTOMER"
    },
    {
        "segmentId": "86103991712541936042017-08-24T13:47:36.435",
        "user": "currentUser",
        "createdDateTime": "2017-08-24T13:47:36.435",
        "segmentName": "division24/08",
        "segmentDefination": "division24/08",
        "segmentFilter": "facilities_12_months_spend >= 12666162&division=NAT",
        "segmentStatus": "Active",
        "segmentCategory": "ACCOUNT_CUSTOMER"
    },
    {
        "segmentId": "8610399171254193719",
        "user": "NewUser",
        "createdDateTime": "2017-08-25T15:15:36.115",
        "segmentName": "satewise 25/08",
        "segmentDefination": "state wise 25/08",
        "segmentFilter": "state = ID",
        "segmentStatus": "Active",
        "segmentCategory": "ACCOUNT_CUSTOMER"
    },
    {
        "segmentId": "8610399171254194503",
        "user": "NewUser",
        "createdDateTime": "2017-08-25T15:17:08.899",
        "segmentName": "check test25/08",
        "segmentDefination": "check test25/08",
        "segmentFilter": "facilities_12_months_spend >= 12666162",
        "segmentStatus": "Active",
        "segmentCategory": "ACCOUNT_CUSTOMER"
    },
    {
        "segmentId": "8610399171254194257",
        "user": "NewUser",
        "createdDateTime": "2017-08-25T18:12:35.653",
        "segmentName": "ssssss",
        "segmentDefination": "assssss",
        "segmentFilter": "facilities_12_months_spend >= 2404670.96",
        "segmentStatus": "Active",
        "segmentCategory": "ACCOUNT_CUSTOMER"
    },
    {
        "segmentId": "8610399171254193688",
        "user": "NewUser",
        "createdDateTime": "2017-08-25T18:14:20.084",
        "segmentName": "suman",
        "segmentDefination": "asadasa",
        "segmentFilter": "facilities_12_months_spend = 3924891.96",
        "segmentStatus": "Active",
        "segmentCategory": "ACCOUNT_CUSTOMER"
    },
    {
        "segmentId": "86103991712541936042017-08-24T15:45:29.036",
        "user": "NewUser",
        "createdDateTime": "2017-08-24T15:45:29.036",
        "segmentName": "rch24/08",
        "segmentDefination": "rch",
        "segmentFilter": "division = RCH",
        "segmentStatus": "Active",
        "segmentCategory": "ACCOUNT_CUSTOMER"
    },
    {
        "segmentId": "86103991712541936042017-08-25T12:59:40.563",
        "user": "NewUser",
        "createdDateTime": "2017-08-25T12:59:40.563",
        "segmentName": "dfff",
        "segmentDefination": "fdgdg",
        "segmentFilter": "facilities_12_months_spend <= 0",
        "segmentStatus": "Active",
        "segmentCategory": "ACCOUNT_CUSTOMER"
    },
    {
        "segmentId": "8610399171254194571",
        "user": "NewUser",
        "createdDateTime": "2017-08-25T18:30:47.967",
        "segmentName": "kunal",
        "segmentDefination": "faciliies",
        "segmentFilter": "facilities_12_months_spend <= 7472073.96",
        "segmentStatus": "Active",
        "segmentCategory": "ACCOUNT_CUSTOMER"
    },
    {
        "segmentId": "8610399171254194052",
        "user": "NewUser",
        "createdDateTime": "2017-08-28T12:38:15.448",
        "segmentName": "Test28/08",
        "segmentDefination": "Test28/08",
        "segmentFilter": "facilities_12_months_spend >= 12666162",
        "segmentStatus": "Active",
        "segmentCategory": "ACCOUNT_CUSTOMER"
    }
];


var ATTRIBUTE_LIST_UPDATED = {
   "ACCOUNT_CUSTOMER_BANK":{
      "Category_Spend":[
         {
            "name":"paper_6_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"promo_3_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"office_supplies_24_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"promo_12_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"furniture_24_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"furniture_3_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"paper_3_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"facilities_12_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"furniture_12_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"toner_3_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"office_supplies_3_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"tech_24_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"facilities_6_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"toner_12_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"paper_24_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"print_6_months_spend ",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"promo_24_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"facilities_24_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"food_and_brkrm_6_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"food_and_brkrm_12_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"paper_12_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"tech_3_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"mail_and_ship_3_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"tech_12_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"tech_6_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"office_supplies_12_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"print_24_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"mail_and_ship_6_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"food_and_brkrm_3_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"mail_and_ship_24_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"facilities_3_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"print_12_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"toner_24_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"toner_6_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"office_supplies_6_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"food_and_brkrm_24_mths_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"mail_and_ship_12_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"print_3_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"furniture_6_months_spend",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"promo_6_months_spend",
            "type":"string",
            "isAdded":false
         }
      ],
      "Identifier":[
         {
            "name":"account_type_code",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"company",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"account_number",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"src_sys_code",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"account_type",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"division",
            "type":"string",
            "isAdded":false
         }
      ],
      "Firmographics":[
         {
            "name":"zip_code",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"state",
            "type":"string",
            "isAdded":false
         }
      ],
      "Membership":[
         {
            "name":"rewards_account_number",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"enrolled_prog",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"memb_start_date",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"rewards_tier",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"rewards_start_dat",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"memb_enrolled_flag",
            "type":"string",
            "isAdded":false
         },
         {
            "name":"memb_end_date",
            "type":"string",
            "isAdded":false
         }
      ]
   }
};

var TABLE_LIST = {
    "result_count": 85923,
    "dataList": [
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        },
        {
            "facilities_12_months_spend": "112.61",
            "food_and_brkrm_12_months_spend": "185.98",
            "furniture_24_months_spend": "245.44",
            "mail_and_ship_24_months_spend": "0.0",
            "promo_3_months_spend": "0.0",
            "toner_12_months_spend": "1215.2",
            "food_and_brkrm_6_months_spend": "22.48",
            "office_supplies_24_months_spend": "1609.04",
            "paper_12_months_spend": "527.12",
            "print_6_months_spend": "0.0",
            "promo_24_months_spend": "0.0",
            "promo_6_months_spend": "0.0",
            "toner_24_months_spend": "1326.38",
            "furniture_12_months_spend": "245.44",
            "furniture_3_months_spend": "0.0",
            "furniture_6_months_spend": "64.99",
            "mail_and_ship_12_months_spend": "0.0",
            "mail_and_ship_3_months_spend": "0.0",
            "mail_and_ship_6_months_spend": "0.0",
            "paper_6_months_spend": "97.97",
            "print_12_months_spend": "0.0",
            "print_3_months_spend": "0.0",
            "facilities_6_months_spend": "11.95",
            "food_and_brkrm_24_mths_spend": "185.98",
            "food_and_brkrm_3_months_spend": "0.0",
            "office_supplies_3_months_spend": "0.0",
            "office_supplies_6_months_spend": "478.38",
            "paper_24_months_spend": "561.11",
            "paper_3_months_spend": "0.0",
            "print_24_months_spend": "0.0",
            "promo_12_months_spend": "0.0",
            "tech_3_months_spend": "0.0",
            "tech_6_months_spend": "132.89",
            "toner_3_months_spend": "0.0",
            "toner_6_months_spend": "81.99",
            "facilities_24_months_spend": "112.61",
            "facilities_3_months_spend": "0.0",
            "office_supplies_12_months_spend": "1405.68",
            "tech_12_months_spend": "459.1",
            "tech_24_months_spend": "459.1",
            "account_number": "1635437",
            "account_type": "SCC",
            "account_type_code": "100021",
            "company": "001",
            "division": "LA",
            "src_sys_code": "08",
            "rewards_tier": "NA",
            "memb_end_date": null,
            "memb_enrolled_flag": "N",
            "memb_start_date": null,
            "enrolled_prog": null,
            "rewards_account_number": null,
            "rewards_start_date": null,
            "state": "ID",
            "zip_code": "83815"
        }],
    };

    var ATTRIBUTE_DESCRIPTION_ = {
        "maxValue":7512402.0,
        "minValue":-120000.0
        };

    var ATTRIBUTE_DESCRIPTION = [
        "DE",
        "TX",
        "FL",
        "NV",
        "WA",
        "NY",
        "SC",
        "SD",
        "WI",
        "MA",
        "MD",
        "IA",
        "ME",
        "OH",
        "GA",
        "ID",
        "MI",
        "OK",
        "CA",
        "WV",
        "UT",
        "MN",
        "WY",
        "MO",
        "IL",
        "OR",
        "IN",
        "MS",
        "MT",
        "KS",
        "AL",
        "VA",
        "CO",
        "KY",
        "PA",
        "CT",
        "AR",
        "NC",
        "LA",
        "NE",
        "RI",
        "AZ",
        "TN",
        "NH",
        "NJ",
        "VT",
        "DC",
        "NM"
        ];
    
